### ISSUE TITLE
[Improvements] Compiling Instructions missing (Godot project only)

### ISSUE THREAD

**Issue by 0n1cOn3** [unknown-horizons/godot-port#110]
Essential compilation instructions with Godot are missing. 
It is not impossible to find out yourself, but it takes a long time if you have never heard of Godot before. 

A more detailed guide on how to compile this with Godot Engine is desired.

**Comment by LinuxDonald** [comment]
You don’t need to compile UH. It uses gdscript and can directly excuted in the editor. But we will add some information on GitHub about it.

**Comment by 0n1cOn3** [comment]
> You don’t need to compile UH. It uses gdscript and can directly excuted in the editor. But we will add some information on GitHub about it.

Thanks for your information!

Well, I have no clue about Godot at all, so I dont know where I can do that exactly ^^. 
I might be blind and have overseen some instructions in the README.md file.

**Comment by Zireael07** [comment]
@0n1cOn3 literally download the project, download Godot editor, open project in editor, enjoy!

**Comment by pingwindev** [comment]
Instructions and coding related notes are included in the [CONTRIBUTING.md](https://github.com/unknown-horizons/godot-port/blob/develop/CONTRIBUTING.md).

The files rely on Godot 3.5 right now and will be superseded by 4.0 soon. #108

**Comment by LinuxDonald** [comment]
@artism90 we should link that in the readme

**Comment by 0n1cOn3** [comment]
@LinuxDonald 
Im agree.

I would have liked to compile the project myself but the instructions are just not clear. 
Furthermore, I compile on my compiler machine which is headless. 
Therefore the GUI editor is rather unsuitable for me. 

I have compiled a lot of things, but this is just too spooky for me when the compilation instructions are given under Contribution. 
This would be, in my opinion, as a separate topic clearly in the README to indicate or at least a link to it. 
Is not given, however, and the gathering of the information is still time-consuming for me, especially in this project. 

Too bad, I would have liked to play it, but all these circumstances make it impossible for myself.
And please don't come with "Use the pre-compiled binary"... thanks

**Comment by LinuxDonald** [comment]
The game is not in an playable state. For that you will need to wait. When we will release something.
