### ISSUE TITLE
Try to import our tile grapfics

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/godot-port#15]
Try to import our tile graphics that mapper could create an development map.

https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx/base/moderate

**Comment by yigitozdemir** [comment]
I am adding a new pull request for this.

edit: #39 created for this issue.

2nd edit: I think importing existing assets is very important to create a structure and general testing environment as fast as possible. After importing those images i can work on importing more images and sounds to game.

**Comment by YeldhamDev** [comment]
Those are already in with a top-view rendering, as the world is now 3D with a faux-2D style, those are no longer needed.
