### ISSUE TITLE
Singleplayer Start Menu GUI

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/godot-port#16]
Thats the style of the old gui:
![bildschirmfoto_2019-01-14_15-38-33](https://user-images.githubusercontent.com/1757651/51119274-b7953e00-1812-11e9-9924-ff021eb85aed.png)

**Comment by aaronfranke** [comment]
With a few exceptions of buttons that don't work yet, this has been fixed by https://github.com/unknown-horizons/godot-port/pull/43
