### ISSUE TITLE
Use Godot 3.1?

### ISSUE THREAD

**Issue by Jummit** [unknown-horizons/godot-port#31]
In Godot 3.1 optional typing and the 'class_name' keyword get added, which are incredibly useful and make it easier to work together. Since it is nearly finished, it could be a good idea to start in 3.1 since upgrading from 3 to 3.1 would make us more work.

EDIT: It also has GLES2 support which might be needed for some devs with older computer or laptops.

**Comment by YeldhamDev** [comment]
I also want to use 3.1, but If we were to switch to it before reaching full stable, we should at least wait for a release candidate.

**Comment by LinuxDonald** [comment]
You could work in an branch with version 3.1 and merge it after release of 3.1

**Comment by aaronfranke** [comment]
I don't see why we can't just wait a month or two for 3.1 stable. We decided on 3.0 awhile ago.

**Comment by YeldhamDev** [comment]
Closed by 75f78c3.
