### ISSUE TITLE
Use GDQuests code guidelines?

### ISSUE THREAD

**Issue by Jummit** [unknown-horizons/godot-port#36]
GDQuest has made some cool guidelines for GDscript / Godot in general I think we could use:
https://github.com/GDquest/kickstarter-quest-3/blob/4765997a54413022ff5c1a4e29eaf7b31f8ceaa6/docs/code-guidelines.md
I find them super useful for collaborating and also just for my own projects. They are meant for 3.1, but maybe we can use them when we switch to that version.

**Comment by aaronfranke** [comment]
~~Why does he use stray colons before equal signs? Don't equal signs by themselves work fine?~~

**Comment by plexsoup** [comment]
> Don't equal signs by themselves work fine?

They're trying to use static typing.  ( var variableName : typeName = value )
Godot will attempt to infer a type if you omit the type name. ( var variableName : = value )
I'm not sure why they've decided to omit the type names though.

**Comment by YeldhamDev** [comment]
We're currently in 3.0.6, so we'll have to wait to use typing, but's definitely in the plans!

**Comment by Jummit** [comment]
Here we go! 3.1 is out and we can start porting to it!
(And use these guidelines!)

**Comment by YeldhamDev** [comment]
As with 4670b3d, I think this can be closed now.
