### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by njskalski** [unknown-horizons/godot-port#41]
Hi,

I installed Godot from official website and placed it in .local/bin/Godot/3.1/Godot as deduced from build script, ran build.sh on Mint 19 and got errors. Can you try to create a simple Travis CI to provide example environment?

I won't promise any contributions at this point, but I worked at Flying Wild Hog, love Anno series and wanted to learn Godot anyway, so maybe...

**Comment by Calinou** [comment]
You don't *have* to use the `build.sh` and `run.sh` scripts, you can just import the cloned repository as a Godot project. See [Introduction to the editor interface](http://docs.godotengine.org/en/latest/getting_started/step_by_step/intro_to_the_editor_interface.html) for a graphical way of doing this, or [Command-line tutorial](http://docs.godotengine.org/en/latest/getting_started/editor/command_line_tutorial.html) to do it in the command-line. This way, you can run the project directly from the editor.

**Comment by aaronfranke** [comment]
Before running the scripts, you should open the game in the Godot editor. Building depends on having files generated in the `.import/` folder which is generated by the editor.

**Comment by Calinou** [comment]
@aaronfranke The `--export` switch will import assets automatically if needed, so there's no need to do that if you just plan on exporting the project (and not running it directly).

**Comment by njskalski** [comment]
works, thanks!
