### ISSUE TITLE
Archive old repo?

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/godot-port#45]
Yesterday I posted a few bugs on <https://github.com/unknown-horizons/unknown-horizons>. But I didn't know this repository is dead. Sorry for the trouble. But in my defense, I just didn't see it. The notification was hidden for me. I didn't scroll down all the way to the readme to see the message.

The repo description is “Unknown Horizons official code repository http://unknown-horizons.org”, which is now highly misleading.

On <http://unknown-horizons.org/get-involved/> all links point to the old repo.

The old repo is not in archive mode. But probably it should be put into archive mode? This is a feature in GitHub that can be activated for any repo. When active, the repo is essentially read-only, with no new issues or PRs being allowed. Also, there's a highly visible yellow warning above archived repos.

Please make the notifications more visible so that fools like me don't spam the old repo ever again.

**Comment by Calinou** [comment]
Note to maintainers: Make sure to edit the repository's description and README *before* archiving it, as you can't edit it once it's archived. You can still unarchive it at any time though.

**Comment by LinuxDonald** [comment]
The repo will not yet get archived. After the po files are merged into the godot version. And weblate is changed to the new repo. The old repo will get be closed. I will close this ticket.
