### ISSUE TITLE
Create Main Menu

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/godot-port#6]
Recreate the old Main Menu:

![bildschirmfoto_2019-01-13_16-56-44](https://user-images.githubusercontent.com/1757651/51087605-ba7e2900-1755-11e9-8385-382002d9da40.png)

**Comment by aaronfranke** [comment]
https://github.com/unknown-horizons/godot-port/pull/9 I couldn't find the button texture used for the menu.

**Comment by LinuxDonald** [comment]
All main menu icons are here: https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gui/icons/mainmenu

Inactive and Active versions.

**Comment by aaronfranke** [comment]
It's not in there. All the icons that go on top of the button are in there, but not the button background.

**Comment by LinuxDonald** [comment]
Thats the button image: https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gui/images/buttons/mainmenu_button_bg.png

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gui/images/background/mainmenu/wheel.png

**Comment by aaronfranke** [comment]
![d](https://user-images.githubusercontent.com/1646875/51146914-4c556700-1826-11e9-8fb9-0358acdd81a9.png) Everything except the text is done.

**Comment by LinuxDonald** [comment]
Text is done.
