### ISSUE TITLE
Non-Discord contributions

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/godot-port#73]
Someone asked in FreeGameDev today:

> Since it seems to be required for willing contributors to join those channels, i would like to know if they are bridged somewhere non discord.

So, is it true? Is it required to be on Discord to collaborate at all? What will one be missing out when one's not on Discord?

Note: Discord is not FOSS, so it will scare away some potential FOSS contributors.

**Comment by LinuxDonald** [comment]
Everyone can help on the project. Discord is not needed for it. I will think about an solution for this.

**Comment by LinuxDonald** [comment]
We are now have an bridge for discord <-> irc. Now we have to ways how we can communicate.
