### ISSUE TITLE
The discord https://discord.gg/VX6m2ZX can't be logged in.

### ISSUE THREAD

**Issue by uniqss** [unknown-horizons/godot-port#97]
**OS/device including version:**

**Issue description:**

I tried severial times, still failed, the verification is so great that I can't be verified as not a robot.

**Screenshots of issue:**

**Comment by LinuxDonald** [comment]
What is the problem?

**Comment by pingwindev** [comment]
Off-topic. This isn't project-related. Please refer to the Discord communication channels for support.

If, for some reason, you still verify as a robot, there are alternative discussion channels for the project:
IRC: https://kiwiirc.com/nextclient/irc.libera.chat/#unknown-horizons
Forum: https://forum.freegamedev.net/viewforum.php?f=100
