### ISSUE TITLE
numbers don't fit für BoxShape4x4 and BoxShape4x4Flat

### ISSUE THREAD

**Issue by theHacker** [unknown-horizons/godot-port#98]
Hi guys,
I was just browsing the code and noticed something odd with the numbers of the `BoxShape` thingies:
- `BoxShape1x1` has `Vector3(0.5, 0.5, 0.5)`
- `BoxShape2x2` has `Vector3(1, 0.5, 1)`
- `BoxShape4x2` has `Vector3(2, 0.5, 1)`
- `BoxShape6x6` has `Vector3(3, 0.5, 3)`

However
- `BoxShape4x4` only has `Vector(1.5, 0.5, 1.5)` – shouldn't that be `Vector(2, 0.5, 2)`? or name it `BoxShape3x3`?
- analog for `BoxShape4x4Flat`: `Vector3( 1.5, 0.05, 1.5 )` instead of likely `Vector3( 2, 0.05, 2 )` or `BoxShape3x3Flat`

**Comment by pingwindev** [comment]
Yes, the vector is right, the naming isn't. I assume I shortly turned it into a 3x3 afterwards, and as there was no actual 4x4 flavored shape necessary so far, this didn't come up. Thanks for the note.
